<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="MimeKit" Version="4.8.0" />
    <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SitioVentas.Constants\SitioVentas.Constants.csproj" />
    <ProjectReference Include="..\SitioVentas.Dto\SitioVentas.Dto.csproj" />
    <ProjectReference Include="..\SitioVentas.Entities\SitioVentas.Entities.csproj" />
    <ProjectReference Include="..\SitioVentas.Repository\SitioVentas.Repository.csproj" />
  </ItemGroup>

</Project>
